AllCops:
  Exclude:
    - "bin/*"
    - "vendor/**/*"
  TargetRubyVersion: 2.3

Layout/IndentFirstArrayElement:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 200

Metrics/LineLength:
  Max: 96

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - "Gemfile*"
    - "Rakefile"
    - "*.gemspec"
    - "spec/**/*"

Style/IfUnlessModifier:
  Enabled: false

# Turn this on in the future
Style/Documentation:
  Enabled: false

# Extend self preserves private methods
Style/ModuleFunction:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Style/StringLiterals:
  EnforcedStyle: double_quotes
